# See: https://www.dartlang.org/tools/pub/pubspec
name: flutter_sqlcipher
version: 0.0.0
description: >-
  SQLCipher for Flutter
author: Arto Bendiken <arto@bendiken.net>
homepage: https://github.com/drydart/flutter_sqlcipher
documentation:
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  test: '>=1.3.4 <2.0.0'
dependency_overrides:
environment:
 sdk: '>=2.0.0 <3.0.0'
executables:
flutter:
  plugin:
    androidPackage: com.github.drydart.flutter_sqlcipher
    pluginClass: FlutterSQLCipherPlugin
